SELECT * FROM BANKACCOUNT;

CREATE TABLE AccountUser (
UserName VARCHAR2(30),
UserPass VARCHAR2(30),
UserID NUMBER,
PRIMARY KEY (UserID)
);

CREATE SEQUENCE USERSEQ;
CREATE SEQUENCE ACCSEQ;



SELECT * FROM AccountUser;

CREATE TABLE BankAccount (
AccountBalance NUMBER,
AccountID NUMBER,
UserID NUMBER,
PRIMARY KEY (AccountID),
FOREIGN KEY(UserID) REFERENCES AccountUser(UserID)
);


ALTER TABLE BANKACCOUNT MODIFY ACCOUNTBALANCE NUMBER(15,2);


SELECT * FROM AccountUser;
SELECT * FROM BankAccount;
DESC BANKACCOUNT;
SELECT * FROM BANKACCOUNT WHERE USERID=41;




CREATE TABLE BankAccount(userName VARCHAR2(30), userPass VARCHAR2(30), userID INT NOT NULL, PRIMARY KEY(userID));
SELECT * FROM BANKACCOUNT;

CREATE OR REPLACE PROCEDURE spDeposit(BANKACCOUNTID NUMBER, amount NUMBER)
IS 
BEGIN
UPDATE BANKACCOUNT SET ACCOUNTBALANCE = ACCOUNTBALANCE+amount WHERE accountid = BANKACCOUNTID;
END;
/
execute spDeposit();
DESC BANKACCOUNT;
CREATE OR REPLACE PROCEDURE spWithdraw(BANKACCOUNTID NUMBER, amount NUMBER)
IS 
BEGIN
UPDATE BANKACCOUNT SET ACCOUNTBALANCE = ACCOUNTBALANCE-amount WHERE accountid = BANKACCOUNTID;
END;
/

CREATE OR REPLACE PROCEDURE spDelete(BANKACCOUNTID NUMBER)
IS
BEGIN
DELETE FROM BANKACCOUNT WHERE ACCOUNTID=BANKACCOUNTID;
END;
/
