/*DB Creation*/

CREATE SEQUENCE CUSTSEQ;
CREATE SEQUENCE ACCTSEQ;

CREATE TABLE BANKUSERS(
USER_ID NUMBER PRIMARY KEY,
USER_USERNAME VARCHAR2(30),
USER_PASSWORD VARCHAR2(30),
USER_FIRSTNAME VARCHAR2(30),
USER_LASTNAME VARCHAR2(30)
);

CREATE TABLE ACCOUNTS(
ACCT_ID NUMBER PRIMARY KEY,
ACCT_NAME VARCHAR2(100),
ACCT_FUNDS NUMBER(5, 2),
USER_ID NUMBER
);

ALTER TABLE ACCOUNTS
ADD CONSTRAINT FK_USER_ID
FOREIGN KEY(USER_ID) REFERENCES BANKUSERS(USER_ID);

/*Stored Procedures*/

-----------------User Account Procedures------------------

CREATE OR REPLACE PROCEDURE CREATEUSERACCOUNT(UNAME IN VARCHAR2, PWORD IN VARCHAR2, FNAME IN VARCHAR2, LNAME IN VARCHAR2) IS
BEGIN
    INSERT INTO BANKUSERS VALUES(CUSTSEQ.NEXTVAL, UNAME, PWORD, FNAME, LNAME);
END;
/

CREATE OR REPLACE PROCEDURE UPDATEUSERACCOUNT(U_ID IN NUMBER, NEWVALUE IN VARCHAR2, CHOICE IN NUMBER) IS
BEGIN
    CASE
        WHEN CHOICE = 1 THEN UPDATE BANKUSERS SET USER_USERNAME = NEWVALUE WHERE USER_ID = U_ID;
        WHEN CHOICE = 2 THEN UPDATE BANKUSERS SET USER_PASSWORD = NEWVALUE WHERE USER_ID = U_ID;
        WHEN CHOICE = 3 THEN UPDATE BANKUSERS SET USER_FIRSTNAME = NEWVALUE WHERE USER_ID = U_ID;
        WHEN CHOICE = 4 THEN UPDATE BANKUSERS SET USER_LASTNAME = NEWVALUE WHERE USER_ID = U_ID;
    END CASE;
END;
/

CREATE OR REPLACE PROCEDURE DELETEUSERACCOUNT(USERID IN NUMBER) IS
BEGIN
    DELETE FROM BANKUSERS WHERE USER_ID = USERID;
END;
/

-----------------Bank Account Procedures------------------

CREATE OR REPLACE PROCEDURE CREATEBANKACCOUNT(U_ID IN NUMBER, ACCTNAME IN VARCHAR2, FUNDS IN NUMBER) IS
BEGIN
    INSERT INTO ACCOUNTS VALUES(ACCTSEQ.NEXTVAL, ACCTNAME, FUNDS, U_ID);
END;
/

CREATE OR REPLACE PROCEDURE WITHDRAW(ACCTID IN NUMBER, FUNDS IN NUMBER) IS
BEGIN
    UPDATE ACCOUNTS SET ACCT_FUNDS = ACCT_FUNDS - FUNDS WHERE ACCT_ID = ACCTID;
END;
/

CREATE OR REPLACE PROCEDURE DEPOSIT(ACCTID IN NUMBER, FUNDS IN NUMBER) IS
BEGIN
    UPDATE ACCOUNTS SET ACCT_FUNDS = ACCT_FUNDS + FUNDS WHERE ACCT_ID = ACCTID;
END;
/

CREATE OR REPLACE PROCEDURE DELETEBANKACCOUNT(ACCTID IN NUMBER) IS
BEGIN
    DELETE FROM ACCOUNTS WHERE ACCT_ID = ACCTID;
END;
/

COMMIT;
