CREATE TABLE SUPERHERO(
HEROID NUMBER PRIMARY KEY,
HERONAME VARCHAR2(50)
);

CREATE TABLE SUPERPOWER(
POWERID NUMBER PRIMARY KEY,
POWERNAME VARCHAR2(50)
);

CREATE SEQUENCE HEROSEQ;
CREATE SEQUENCE PWRSEQ;

CREATE OR REPLACE PROCEDURE INSERTSUPERHERO(NAME IN VARCHAR2) AS
BEGIN
    INSERT INTO SUPERHERO VALUES(HEROSEQ.NEXTVAL, NAME);
    COMMIT;
END;
/

ALTER TABLE SUPERHERO ADD POWERID NUMBER;

ALTER TABLE SUPERHERO ADD FOREIGN KEY (POWERID) REFERENCES SUPERPOWER(POWERID);

CREATE OR REPLACE PROCEDURE CREATEHEROANDPOWER(HNAME IN VARCHAR2, PNAME IN VARCHAR2) AS
BEGIN
    INSERT INTO SUPERPOWER VALUES(PWRSEQ.NEXTVAL, PNAME);
    INSERT INTO SUPERHERO VALUES(HEROSEQ.NEXTVAL, HNAME, PWRSEQ.CURRVAL);
    COMMIT;
END;
/

EXEC CREATEHEROANDPOWER('Superman', 'Super Strength');