
package com.revature.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-08-07T16:43:04.272-04:00
 * Generated source version: 3.1.6
 * 
 */
public final class MessageGen_MessageGenImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.revature.com/", "messageGenService");

    private MessageGen_MessageGenImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MessageGenService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MessageGenService ss = new MessageGenService(wsdlURL, SERVICE_NAME);
        MessageGen port = ss.getMessageGenImplPort();  
        
        {
        System.out.println("Invoking getMessage...");
        java.lang.String _getMessage__return = port.getMessage();
        System.out.println("getMessage.result=" + _getMessage__return);


        }

        System.exit(0);
    }

}
